CONTIKI_TARGET_DIRS = . apps net
CONTIKI_CORE=contiki-dp-webplatform
CONTIKI_TARGET_MAIN = ${CONTIKI_CORE}.o

WP_NET = enc28j60.c enc28j60-drv.c
CONTIKI_TARGET_SOURCEFILES += contiki-dp-webplatform-main.c leds-arch.c serial.c $(WP_NET)

DEV     += leds.c

CONTIKIPIC=$(CONTIKI)/cpu/dspic
CONTIKIBOARD=.

CONTIKI_NO_NET=1

CONTIKI_PLAT_DEFS=

CONTIKI_SOURCEFILES += $(CONTIKI_TARGET_SOURCEFILES)

include $(CONTIKIPIC)/Makefile.dspic
